import Head from 'next/head'
import Link from 'next/link';

const PageLayout = ({ children, title = "NewsApp" }) => {


    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <div>
                    <Link href='/'>🗞  newsAPI</Link>

                </div>
                <div>
                    <Link href='/About'>Ir a about</Link>
                </div>
            </header>
            <main>
                {children}
            </main>
            <style jsx>{`
                header {
                    display:flex;
                    justify-content: space-between;
                    padding:20px;
                }
                `}
            </style>
        </>
    );
}

export default PageLayout;